service: ads-management-api

provider:
  name: aws
  architecture: arm64
  runtime: provided.al2
  region: '${opt:region, self:custom.defaultRegion}'
  stage: ${opt:stage, self:custom.defaultEnvStage}
  profile: ${opt:profile, 'serverless'}
  timeout: 60

  environment:
    STAGE: '${opt:env-stage, self:custom.defaultEnvStage}'
package:
  individually: true
  patterns:
    - "!node_modules/**"

custom:
  go:
    cgo: 0
    cmd: GOARCH=arm64 G00S=linux go build -ldflags="-s -w"
    supportedRuntimes: [ "provided.al2" ]
    buildProvidedRuntimeAsBootstrap: true
  defaultRegion: ap-northeast-1
  defaultEnvStage: local

  environment:
    stg: ${file(./config/sls_env/stg.yml)}
    prd: ${file(./config/sls_env/prd.yml)}
    local: ${file(./config/sls_env/local.yml)}
  
  prune:
    automatic: true
    number: 3
  
  
  